[project]
name = "icev-scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gooey>=1.0.8.1",
    "six>=1.17.0",
]
